from typing import Any

from ....models import PlannedFile


def _param(parameters: dict[str, Any], *names: str, default: str) -> str:
    for name in names:
        value = parameters.get(name)
        if value is not None and str(value).strip():
            return str(value).strip()
    return default


def _openfoam_header(class_name: str, object_name: str) -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Generated by SimAgent                           |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {class_name};
    object      {object_name};
}}
"""


def render_control_dict(parameters: dict[str, Any]) -> str:
    end_time = _param(parameters, "end_time", "endTime", "final_time", "finalTime", default="0.5")
    delta_t = _param(parameters, "delta_t", "deltaT", "time_step", "timestep", default="0.005")
    write_interval = _param(parameters, "write_interval", "writeInterval", default="20")
    return _openfoam_header("dictionary", "controlDict") + f"""
application     icoFoam;

startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time};
deltaT          {delta_t};

writeControl    timeStep;
writeInterval   {write_interval};
purgeWrite      0;

writeFormat     ascii;
writePrecision  6;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable true;
"""


def render_fv_schemes() -> str:
    return _openfoam_header("dictionary", "fvSchemes") + """
ddtSchemes
{
    default         Euler;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
    div(phi,U)      Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear orthogonal;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         orthogonal;
}
"""


def render_fv_solution() -> str:
    return _openfoam_header("dictionary", "fvSolution") + """
solvers
{
    p
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-06;
        relTol          0.05;
    }

    pFinal
    {
        $p;
        relTol          0;
    }

    U
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-05;
        relTol          0;
    }
}

PISO
{
    nCorrectors     2;
    nNonOrthogonalCorrectors 0;
    pRefCell        0;
    pRefValue       0;
}
"""


def render_block_mesh_dict() -> str:
    return _openfoam_header("dictionary", "blockMeshDict") + """
convertToMeters 1;

vertices
(
    (0 0 0)
    (1 0 0)
    (1 1 0)
    (0 1 0)
    (0 0 0.1)
    (1 0 0.1)
    (1 1 0.1)
    (0 1 0.1)
);

blocks
(
    hex (0 1 2 3 4 5 6 7) (20 20 1) simpleGrading (1 1 1)
);

edges
(
);

boundary
(
    movingWall
    {
        type wall;
        faces
        (
            (3 7 6 2)
        );
    }
    fixedWalls
    {
        type wall;
        faces
        (
            (0 4 7 3)
            (2 6 5 1)
            (1 5 4 0)
        );
    }
    frontAndBack
    {
        type empty;
        faces
        (
            (0 3 2 1)
            (4 5 6 7)
        );
    }
);

mergePatchPairs
(
);
"""


def render_physical_properties(parameters: dict[str, Any]) -> str:
    nu = _param(parameters, "nu", "viscosity", "kinematic_viscosity", default="0.01")
    return _openfoam_header("dictionary", "physicalProperties") + f"""
nu              [0 2 -1 0 0 0 0] {nu};
"""


def render_u(parameters: dict[str, Any]) -> str:
    lid_velocity = _param(parameters, "lid_velocity", "top_velocity", "velocity", default="1")
    return _openfoam_header("volVectorField", "U") + f"""
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 0);

boundaryField
{{
    movingWall
    {{
        type            fixedValue;
        value           uniform ({lid_velocity} 0 0);
    }}

    fixedWalls
    {{
        type            noSlip;
    }}

    frontAndBack
    {{
        type            empty;
    }}
}}
"""


def render_p() -> str:
    return _openfoam_header("volScalarField", "p") + """
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    movingWall
    {
        type            zeroGradient;
    }

    fixedWalls
    {
        type            zeroGradient;
    }

    frontAndBack
    {
        type            empty;
    }
}
"""


def render_case_files(parameters: dict[str, Any]) -> list[tuple[PlannedFile, str]]:
    return [
        (PlannedFile("control", "case/system/controlDict", "openfoam-dict"), render_control_dict(parameters)),
        (PlannedFile("numerics", "case/system/fvSchemes", "openfoam-dict"), render_fv_schemes()),
        (PlannedFile("linear_solver", "case/system/fvSolution", "openfoam-dict"), render_fv_solution()),
        (PlannedFile("mesh", "case/system/blockMeshDict", "openfoam-dict"), render_block_mesh_dict()),
        (PlannedFile("physical_properties", "case/constant/physicalProperties", "openfoam-dict"), render_physical_properties(parameters)),
        (PlannedFile("initial_condition", "case/0/U", "openfoam-dict"), render_u(parameters)),
        (PlannedFile("initial_condition", "case/0/p", "openfoam-dict"), render_p()),
    ]
